# Generated by Django 2.1.7 on 2019-02-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_estudiante_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pagos',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
